name: CI

on:
  push:
  pull_request:

jobs:
  comprobacion:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Comprobar archivos del proyecto
        run: |
          echo "CI ejecutándose correctamente"
          ls